{{- if not .Values.existingSecrets.apiKeys -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stream-monitor.fullname" . }}-secrets
  labels:
    {{- include "stream-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.secrets.apiKey | quote }}
  internal-api-key: {{ .Values.secrets.internalApiKey | quote }}
  webhook-signing-key: {{ .Values.secrets.webhookSigningKey | quote }}
{{- end }}
